name: TownyWars
version: 0.1
authors: [VoxelBuster,drkmatr1984,MikeST,TimeLord,caarson]
main: net.realmoftowny.townywars.TownyWars
depend: [Towny]
commands:
  twar:
    permission: townywars.help
    aliases: [tw, twars, townywars]